- hosts: app
  tasks:
    - name: Pull image
      command: docker pull ttl.sh/jorgeajimenezl-app:latest

    - name: Stop container
      command: /bin/bash -c 'docker stop $(docker ps -aq --filter ancestor=ttl.sh/jorgeajimenezl-app:latest)'
      
    - name: Run container
      command: docker run -d -p 4444:4444 ttl.sh/jorgeajimenezl-app:latest
