- hosts: app
  tasks:
    # - name: Run container
    #   docker_container:
    #     name: app
    #     image: ttl.sh/jorgeajimenezl-app:latest
    #     state: started
    #     ports:
    #       - "4444:4444"
    - name: Pull image
      command: docker pull ttl.sh/jorgeajimenezl-app:latest

    - name: Run container
      command: docker run -d -p 4444:4444 ttl.sh/jorgeajimenezl-app:latest
